### ISSUE TITLE
Bug de téléportation en début de partie

### ISSUE THREAD

**Issue by NikosDevMC** [leomelki/LoupGarou#10]
Bonjour, en 1er lieu j'utilise bien protocol lib et spigot 1.15.1.
Le bug intervient en début de partie qu'importe le nombre de joueurs.
En effet, j'ai beau set les positions en effaçant les anciennes dans le config.yml et en effectuant /lg addSpawn sur chaque position, les personnes sont téléporté aléatoirement sur un des spawns sans prendre en compte si la place est déjà prise.
Cela conduit à avoir plusieurs personnes sur la même demi-dalle.
Aucune erreur de console.

**Comment by Nicooow** [comment]
Plusieurs parties jouer et je n'ai jamais eu ce problème sur les deux maps,
quand tu les supprimes du fichier config, est-ce que tu penses à bien reload ?

**Comment by NikosDevMC** [comment]
Problème résolu.
J'avais oublié qu'il fallait /lg reloadconfig une fois les anciennes positions delete.

**Comment by Rigner** [comment]
Cette issue peut être fermée.
