### ISSUE TITLE
Impossible de casser des blocs

### ISSUE THREAD

**Issue by pixelroll** [leomelki/LoupGarou#12]
Bonjour,
Il met actuellement impossible de casser des blocs.
Est ce que c'est t'une fonction du plugin ?
Si oui, y a-t-il un moyen de désactiver cela ?
Une permission ou autres.
Merci

**Comment by LordThomDev** [comment]
Hello, si tu veux modifier ta map tu peux unload le plugin le temps de faire les modifs, puis le load quand tu as terminé

**Comment by leomelki** [comment]
Il faut unload le plugin lorsque vous ne l'utilisez pas (avec plugman ou en l'enlevant de  votre dossier plugins puis en recheargant le serveur (restart ou /rl))
