### ISSUE TITLE
Enlever le pack de ressources

### ISSUE THREAD

**Issue by tomlahaye** [leomelki/LoupGarou#15]
Est-il possible d'enlever le pack de ressources, pour intégrer le plugin sur un serveur ayant déjà d'autres maps et donc ne pas utiliser le pack de ressources sur les autres maps ?

**Comment by tomlahaye** [comment]
Après réfléxion ma demande n'est pas clair ! 

J'ai actuellement un serveur avec le plugin Loup Garou et également un serveur avec un monde survie les deux sont lier avec bungeecord, tout fonctionne nickel sauf que quand je vais sur le serveur avec le loup garou, le texture packs ce met en place, mais si je retourne sur le serveur survie le texture pack reste et il faut deco reco pour qu'il s'enleve

**Comment by ineanto** [comment]
De base c'est géré automatiquement par le client. Ton serveur est sous quelle version ?

**Comment by tomlahaye** [comment]
Ah ça n’a pas l’air de fonctionner , je suis en 1.15.1

**Comment by leomelki** [comment]
Le pack de ressource se télécharge automatiquement à la connexion au serveur. S'il ne se télécharge pas, c'est que le plugin ne démarre pas correctement.

Etes vous sur que vous utilisez SPIGOT 1.15.1 ?
