### ISSUE TITLE
Bug au lancement 'pas assez de spawn'

### ISSUE THREAD

**Issue by vozxc** [leomelki/LoupGarou#16]
Je me suis mis sur les dalles et set les spawn mais quand je lance la game ça me dit qu'il n'y a pas assez de points de spawn.

**Comment by jturazzi** [comment]
@vozxc https://loup-garou.tr1nity.ovh/

**Comment by vozxc** [comment]
dsl j'ai pas vu cette question dans le readme 'J’ai plusieurs personnes sur la même dalle que faire ?' merci pour l'info
