### ISSUE TITLE
Impossible de courir

### ISSUE THREAD

**Issue by QuentinAutret** [leomelki/LoupGarou#22]
Bonjour,

Tout d'abord, merci beaucoup pour le plugin, il est génial 👍 
Cependant, les joueurs avec qui je joue souhaitent que je rajoute un jump parkour sur ma map. Le problème étant que le plugin LG met tout les joueurs à 3 de nourriture et donc empêche de courir, c'est assez frustrant.

C'est possible de réactiver le sprint?

**Comment by Nicooow** [comment]
Leomelki a déjà expliqué pour la nourriture était à 6 : [ici](https://github.com/leomelki/LoupGarou/pull/19#pullrequestreview-379569300)

**Comment by QuentinAutret** [comment]
Ah oui d'accord, pas de soucis, c'est dommage mais si y a pas le choix faut faire avec
