### ISSUE TITLE
On peut pas le faire sur nos propre serv ? 

### ISSUE THREAD

**Issue by MisterChaos5** [leomelki/LoupGarou#23]
Salut je me demande si on ne peut pas prendre le plug-in et la map pour les mettre sur notre propre serveur car j'en est 1 avec mes potes ?

**Comment by ArnaudLier** [comment]
Si tu peut le faire, pourquoi?

**Comment by leomelki** [comment]
Vous pouvez bien évidemment faire des serveurs privés pour jouer entre amis, c'est le but !
