### ISSUE TITLE
Initialisation des rôles

### ISSUE THREAD

**Issue by itasli** [leomelki/LoupGarou#26]
Lors de l'initialisation des rôles, le nombre devrait être égale à 0 afinnde faciliter la configuration de partie et non à 1 (je ne sais pas si c'est assez clair ou pas)

**Comment by ArnaudLier** [comment]
Fixed in #27 :D

**Comment by leomelki** [comment]
La proposition de @MrLacpierre semble être meilleure : 

> Si tout est sur 0 par défaut, le message de "a rejoint la partie" ne s'affiche pas et les joueurs ne se voient pas car ils sont considérés comme spectateurs. Je suggère juste de mettre par défaut 26 (ou autre) villageois pour palier à ce soucis comme ça celui qui configure n'a qu'à remettre le bon nombre de villageois tout en configurant les autres rôles.
