### ISSUE TITLE
Probleme d'activation du plugin

### ISSUE THREAD

**Issue by sukrenpoudre** [leomelki/LoupGarou#28]
Bonjour à tous 
Merci a vous d'avoir poster ce superbe mode^^.
Pour ma par j'ai du mal a le mettre en place je ne comprend pas pourquoi mais les commandes ne veulent pas etre reconnu. Je soupsonne que ce soit parce que le plugin n'es pas reconnu mais je vois pas comment régler ca 😅 
Si vous avez la solution vous me sauvez la vie et tuez mon ennui durant ce confinement 😂.

**Comment by Rigner** [comment]
Les fichiers de logs seraient utiles pour comprendre le problème ^^

**Comment by sukrenpoudre** [comment]
Entre temps j'ai compris mon erreur j'utilisais le launcher minecraft serveur et ce dernier ne permet pas les plug in merci de votre aide cependant ^^
