### ISSUE TITLE
Issue with onEntitySpawn when I enter the server

### ISSUE THREAD

**Issue by FlavienAndrieux** [leomelki/LoupGarou#32]
Ok un peu de contexte: J'essaye de faire une traduction en anglais du jeu. 

Du coup, j'ai modifié les Strings liés aux noms de roles et des messages broadcast nécessaire à la compréhension du  déroulement du jeu. Hormis des strings, je n'ai rien modifié d'autres (variables globales, nom de classes, fonctions etc..) nécessaire au bon fonctionnement du code ne sachant pas les dépendances qui existeraient. 

Mais lorsque j'exporte en jar file, j'exporte le src/main/java uniquement avec l'ensemble des packages fournis en utilisant l'option "Export generated class files and ressources" et "Export Java source files and ressources"  et je décoche les fichiers docker et github car ils nous sont inutiles ici.

Me voilà avec mon plugin, je lance le serveur comme il faut (je fais exactement la même méthode qu'avec le plugin original qui fonctionne chez moi). ET là, dès que je spawn, j'ai un message d'erreur qui tourne à l'infini dans les logs du serv. Ce message vient de la procédure onEntitySpawn de la class CancelListener.

Je n'arrive pas à comprendre le lien entre mes modifications et ce problème. Je soupçonne une mauvaise exportation de ma part car ça fait longtemps que je ne fais plus de java.

J'aimerais savoir vos idées, ou sii vous avez une méthode pour le débug et pouvoir suivre ce qu'il s'y passe. car les logs n'affichent absolument rien de plus que le string de la procédure.  Et surtout l'utilité de la procédure onEntitySpawn, ce qu'il permet de faire ou évite. Car je ne comprends pas.

**Comment by FlavienAndrieux** [comment]
Bon je laisse l'issue ouverte mais j'ai commenté le string pour éviter qu'il s'affiche constamment. 
Après un peu plus de reflexion, je pense que la procédure s'appelle tout le temps car il estime que je spawn tout le temps. Est-ce normal? En tout cas ça n'empêche pas le plugin de fonctionner.

**Comment by leomelki** [comment]
Tu as sûrement une ancienne version de la repo. Pense bien à la tenir à
jour. Les issues à propos des anciennes versions vont être constamment
close 😐

Le mar. 31 mars 2020 à 23:38, FlavienAndrieux <notifications@github.com> a
écrit :

**Comment by leomelki** [comment]
Tu as sûrement une ancienne version de la repo. Pense bien à la tenir à jour. Les issues à propos des anciennes versions vont être constamment close 😐
