### ISSUE TITLE
Ressource pack pour jouer

### ISSUE THREAD

**Issue by peaceandcube** [leomelki/LoupGarou#34]
Bonjour, 

Lorsque nous essayons de nous connecter au serveur nous avons cette erreur:

Il vous faut le resourcepack pour jouer ! (DECLINED)

Quel est le ressource pack nécéssaire s'il vous plait ou comment désactiver ce kick auto ?

Merci beaucoup

**Comment by peyrlac** [comment]
Quand vous vous êtes connecté au serveur pour la première fois, vous avez refusé le ressource pack. C'est pour ça que ça vous kick. Pour résoudre le problème, il faut aller dans le menu multijoueur et cliquer sur modifier le serveur pour activer l'utilisation du ressource pack.

**Comment by peaceandcube** [comment]
Merci beaucoup <3
