### ISSUE TITLE
Incompatibilité avec le plugin Skins lors de l'ajout de spawns

### ISSUE THREAD

**Issue by peyrlac** [leomelki/LoupGarou#36]
A cause du [plugin Skins](https://www.spigotmc.org/resources/skins-1-12-x-1-13-2-1-14-x-1-15-x.70829/updates), le plugin Loup Garou génère des coordonnées de spawns en double dans la config.

De mon avis, le plugin Skins récupère l'uuid premium avec le skin. (étant donné que le serveur est en crack, celui-ci donne des uuids random aux joueurs les faisant perdre leur skin). Par la suite, le plugin Skins doit surement générer une marionnette avec le skin (à la manière du [plugin Citizens](https://dev.bukkit.org/projects/citizens)) par dessus le joueur. Du coup, 2 uuids/joueurs déclenchent la commande et générent des spawns doublons. C'est ce que je pense.
(Si jamais, on utilise un serveur crack pour jouer avec des gens qui ne jouent au jeu que pour le Loup Garou et on utilise le plugin Skins car on bascule sur un monde survie quand il y a pas de Loup Garou organisé.)

**Comment by jturazzi** [comment]
Supprime ton fichier de configuration et refait tes spawns tu as du mal les définir.
https://loup-garou.tr1nity.ovh/#jai-plusieurs-personnes-sur-la-m%C3%AAme-dalle-que-faire-

**Comment by peyrlac** [comment]
J'ai résolu le problème en enlevant le plugin problématique et en refaisant les spawns. J'ouvrais juste cette issue pour prévenir du problème (je ne sais pas si c'était la bonne utilisation ou pas, j'utilise peu github)
