### ISSUE TITLE
Probleme de placement de spawn

### ISSUE THREAD

**Issue by PolarisUrsa** [leomelki/LoupGarou#45]
Malgré l'ajout des spawns, il y a toujours deux spawns qui "bloque" les joueurs et les empêchent de jouer proprement (blocage de la vue du personnage et quasi impossibilité de bouger). 
Y a-t-il une maniére d'avoir la liste des spawns parfait ?
Ou de modifier la map pour enlever les éléments gênants (herbe autour des spawns probablement) ?

Merci d'avance.

**Comment by PolarisUrsa** [comment]
Autant pour moi, apres moultes recherches, j'ai trouver ce lien:
https://github.com/jvin042/minecraft-loup-garou-wiki

Merci =)

**Comment by Rigner** [comment]
Cette issue peut être fermée.
