### ISSUE TITLE
[TRADUCTION] Espagnol

### ISSUE THREAD

**Issue by Rakotia** [leomelki/LoupGarou#49]
Bonjour!
Je suis un francophone qui vit en Espagne depuis petit, parfaitement bilingue. Votre projet (vu sur les vidéos de Squeezie) me passione, et c'est pour ça que j'aimerais offrir mon aide: faire une traduction du mod a l'espagnol.
Faites-moi savoir si ça vous intéresse!
Merci :)

**Comment by leomelki** [comment]
Désolé de ne pas avoir répondu plus tôt, j'ai vraiment pas beaucoup de temps à consacrer au Plug-in du loupgarou en ce moment à cause des projets que j'ai à côté, du coup je ne peux pas me permettre de créer de système multi longue pour le moment :/
Cependant, merci beaucoup pour ta proposition !
