### ISSUE TITLE
Idée de nouveux rôle

### ISSUE THREAD

**Issue by garydu21** [leomelki/LoupGarou#51]
Bonjour,
Dans le jeu loup garou (jeu de société) il y a un rôle bien à ajoutés. Se rôle est le Voleur. Il peut échanger sa carte avec un joueur qu'une nuit et se joueur devient donc loup garou pendant que le voleur devient le rôle de la carte volée. Il gagnerait soit avec les villageois, soit avec les loup car je vous rappelle que si il gagne avec le village, il auras quand même peut être volée une carte au chasseur qui est avec lui.

Cordialement

**Comment by leomelki** [comment]
Ce rôle à été ajouté mais, l'ayant ajouté dans une autre version, cela me prendrait trop de temps de l'ajouter ici.
Peut être qu'il arrivera plus tard, qui sais :/
