### ISSUE TITLE
Skin indisponible & Test de remplacement

### ISSUE THREAD

**Issue by yoinqui** [leomelki/LoupGarou#56]
Bonjour,

Depuis peu, aucun skin ne fonctionne sur cette version du loup-garou. Le skin des villageois est différent de celui des vidéos de Squeezie, le skin du capitaine n’apparaît pas et le skin des loups n'apparaît pas la nuit. Serait-il possible de mettre à jour le repo pour refaire fonctionner les skins ?

J'ai également vu que tout se passait au niveau du fichier /src/main/java/fr/leomelki/loupgarou/classes/LGCustomSkin.java. J'ai donc essayé de remplacer les skins avec l'aide du site minecraftskins.com et mineskin.org.

J'ai donc récupéré le code source, j'ai modifié le code source du fichier /src/main/java/fr/leomelki/loupgarou/classes/LGCustomSkin.java et ensuite j'ai compilé un .jar avec le build path JDK 1.8. J'ai remplacé le fichier dans le serveur, cependant au lancement de ce dernier, je rencontre plusieurs erreurs qui bloque le lancement du pluggin.

Je précise également que l'ouverture du code source avec Eclipse à générer plein d'erreurs sans que j'ai modifié quoi que se soit.

Quelqu'un peut m'aider ? Ou mettre à jour le repo (avec les skins de la dernière vidéo, ils sont bien) ?
Je pense principalement à toi, @leomelki , tu pourrais m'indiquer comment faire ? Et si j'y arrive, je pourrai également mettre à jour le repo.

Par ailleurs, j'ai également trouvé des bugs sur certains rôles, il semble être corrigé dans les versions récentes utilisées dans les dernières vidéos de Squeezie, est-ce que le repo va également avoir un coup de neuf ou pas du tout ?

Au passage, c'est un excellent travail, j'adore jouer sur ce mod ! Merci beaucoup aux personnes qui ont contribué à ce projet. C'est de l'excellent travail !

Merci d'avance

![Capture](https://user-images.githubusercontent.com/23256939/81735138-e1a55180-9494-11ea-8e3a-c955e2294b1c.PNG)
![Capture2](https://user-images.githubusercontent.com/23256939/81735140-e23de800-9494-11ea-9032-f5be3ada0578.PNG)

**Comment by yoinqui** [comment]
Ok, j'ai installé Lombok 1.18.10 comme indiqué dans le README. Je suis passé de plus de 2000 erreurs à 8 à l'ouverture du code source sur eclipse. 

J'ai une erreur dans le fichier CustomScoreboardEntry.java dans le dossier scoreboard. Elle concerne le 'Â§' à la ligne 53 qui est un caractère invalide pour l'IDE.

Les autres erreurs sont tous situé dans le fichier des skins à savoir LGCustomSkin.java dans les classes. Ces erreurs concernent l'annotation @RequiredArgsConstructor ainsi que le getter. Et le caractère \ juste avant le name pour le skin du MAYOR.

Est-ce que quelqu'un peut m'aider?

**Comment by yoinqui** [comment]
@TheOptimisticFactory J'ai le même problème sur ta version. Les skins du capitaine, des Loup-Garou et des villageois ne s'affiche pas. Je pense que c'est à cause des modèles mais mnt je ne suis plus sûr. Pourrais-tu m'aider? Merci d'avance

**Comment by ImKyo** [comment]
> Ok, j'ai installé Lombok 1.18.10 comme indiqué dans le README. Je suis passé de plus de 2000 erreurs à 8 à l'ouverture du code source sur eclipse.
> 
> J'ai une erreur dans le fichier CustomScoreboardEntry.java dans le dossier scoreboard. Elle concerne le 'Â§' à la ligne 53 qui est un caractère invalide pour l'IDE.
> 
> Les autres erreurs sont tous situé dans le fichier des skins à savoir LGCustomSkin.java dans les classes. Ces erreurs concernent l'annotation @RequiredArgsConstructor ainsi que le getter. Et le caractère \ juste avant le name pour le skin du MAYOR.
> 
> Est-ce que quelqu'un peut m'aider?

Pour résoudre les problèmes de caractères spéciaux, change l'encoding du projet en UTF-8 dans ses propriétés. Je suis pas sûr pour le reste mais ça devrait déjà résoudre quelques erreurs.

(Note: si tu as déjà retiré les Â et autres caractères invalides du projet tu devras soit les remettre soit ré-importer les fichiers en question, sinon le changement d'encoding ne les changeront pas en leurs caractères valides habituels (§, é, à, etc).)

![Screenshot_1](https://user-images.githubusercontent.com/61420963/82368099-1ffebb80-9a15-11ea-80ae-2186cf0664ae.png)
