### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Link0Darck** [leomelki/LoupGarou#62]
Bonjour,
j'ai lancer le plugin et fait les commande addspawn ect mais apres pour start rien ne ce passe c'est buger sa ce lance pas et le plugin est pas pareille comme j'ai pus le voir sur votre serveur sinon j'adore votre plugin

**Comment by Link0Darck** [comment]
up

**Comment by Link0Darck** [comment]
pouvez vous répondre s'il vous plait

**Comment by Link0Darck** [comment]
@leomelki merci de pas répondre deupuis le 16 juin

**Comment by leomelki** [comment]
Ce problème vient de votre utilisation. Merci de bien suivre la documentation ou de regarder des tutoriels fait par les membres de la communauté.
Tu peux aussi trouver de l'aide sur le Discord de squeezie, ce que tu aurais remarqué en lisant le Readme... https://discord.gg/squeezie

Je ne peux pas m'occuper des problèmes de configuration qu'ont les gens qui ne regardent pas assez la documentation. Désolé.
