### ISSUE TITLE
Impossible de sélectionner un monde où le plugin LG est activé

### ISSUE THREAD

**Issue by NinjaPlasma** [leomelki/LoupGarou#63]
Bonjour,je suis actuellement entrain de faire des test sur un serveur avec les plugin du Mineral Contest et le Loup Garou je n'ai eu aucun problème avec le MC ,car dans la configuration du plugin j'ai pus choisir dans quelle monde le plugin fonctionner ou ne fonctionner pas. Mais je ne peut pas faire de même avec le plugin LG. Est-ce moi qui est loupé une ligne de la config ou est-ce juste une options non implenté dans le plugin ? Si oui serais il possible de l'implenté

**Comment by ghost** [comment]
oui ta reson c'est chiant

**Comment by leomelki** [comment]
On ne peut pas faire ça. Je te conseille de créer deux serveurs minecraft et de lancer celui qu'il faut pour jouer au jeu que tu veux, quand tu veux 👌
