### ISSUE TITLE
[DOCKER] Erreur lors du build du project

### ISSUE THREAD

**Issue by Hugo1380** [leomelki/LoupGarou#65]
**Utilisation :** 

`docker-compose up -d --build`

Aucun ajout ou modification. Repo clonait tel quel.

Error lors de l'étape `mvn clean install`.

**Error log :** 

```
[ERROR] Failed to execute goal on project LoupGarou: Could not resolve dependencies for project fr.leomelki:LoupGarou:jar:1.1.0: Could not find artifact org.spigotmc:spigot:jar:1.15.1-R0.1-SNAPSHOT in spigot-repo (https://hub.spigotmc.org/nexus/content/repositories/snapshots/) -> [Help 1]
```

A savoir cette erreur n'était pas présente il y a 1 mois sur une première instance que j'avais lancé. Donc certainement un changement chez Spigot.

**Comment by Hugo1380** [comment]
Je viens de tester de build le projet sans utiliser Docker, même erreur lors de `mvn clean install`.

**Maven version : Maven 3.6.0**
**OpenJDK version 8**
**Testé sur Ubuntu**

**Comment by DaFray31** [comment]
Hey, 
Je pense avoir trouvé le problème, j'ai fais un pull request [Fix API spigot](https://github.com/leomelki/LoupGarou/pull/67)

**Comment by leomelki** [comment]
J'ai corrigé le problème, vous pouvez désormais de nouveau build l'image docker !

**Comment by flolep2607** [comment]
ca marche toujours pas

**Comment by flolep2607** [comment]
![image](https://user-images.githubusercontent.com/24566964/107403592-97293200-6b05-11eb-91de-55237a81cf6d.png)

**Comment by leomelki** [comment]
Je viens de vérifier et quelques petites choses ont changées donc j'ai update le Dockerfile.
Cependant, tu ne seras pas capable de build l'image docker pour l'instant car les repo de ProtocolLib sont down :/
