### ISSUE TITLE
[Bug] Le pronostiqueur n'a jamais tort

### ISSUE THREAD

**Issue by lautriva** [leomelki/LoupGarou#68]
Dans le code du Pronostiqueur, je ne vois pas de référence à `Math.random()` ou équivalent
Ce qui implique que lors de son tour, il sait forcément le camp personne ciblée puisque ses pronostics sont toujours les bons

Ou peut être que je loupe un truc ?

**Comment by leomelki** [comment]
Le pronostiqueur n'est pas implémenté dans cette version
