### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Slipers** [leomelki/LoupGarou#69]
Hey est ce que @leomelki peut faire une update du plugin ? Maintenant 2 ans que le plugin n'a pas d'update

**Comment by leomelki** [comment]
Désolé, mais la codebase du plugin a été modifiée et implémentée directement dans le système du serveur lg.leomelki.fr, ce qui m'empêche de mettre à jour cette repo. 
Je vais bientôt archiver cette repo et expliquer tout ça dans le readme
