### ISSUE TITLE
Loup Noir inutile dans certain cas

### ISSUE THREAD

**Issue by Nicooow** [leomelki/LoupGarou#7]
Lorsqu'il y a un loup noir, aucun loup normal et un grand méchant loup, le tour des loups normaux ne se passe pas, en conséquent le loup noir ne joue jamais non plus et ne peut donc jamais infecter quelqu'un.
(De plus le grand méchant loup ne fait donc qu'une victime lors de son tour alors qu'il devrait en voter deux, lors de son tour et lors du tour des loups global, qui ne se passe donc pas)

**Comment by leomelki** [comment]
Oui, c'est normal.
On a oublié de le mettre dans le ReadMe mais il faut toujours avoir un loup garou normal min dans les compo si elles possèdent d'autres types de loups garous ou des joueurs qui peuvent devenir LG pour éviter les problèmes. J'essaierais de le rajouter dans le ReadMe quand j'aurais le temps.

Merci beaucoup :)
